[package]
name = "rust_swig"
version = "0.1.6-pre"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
description = "Tool for connecting libraries written in Rust with other languages"
license = "BSD-3-Clause"
keywords = ["swig", "java", "jni", "ffi", "cxx"]
repository = "https://github.com/Dushistov/rust_swig"
documentation = "https://docs.rs/rust_swig"
readme = "../README.md"

[[bin]]
name = "rust_swig"
path = "src/main.rs"
doc = false

[dependencies]
syntex = "0.58.1"
syntex_syntax = "0.58.1"
syntex_pos = "0.58.1"
syntex_errors = "0.58.1"
log = "0.4"
petgraph = "0.4.5"
lazy_static = "1.0.0"
bitflags = "1.0"

[dev-dependencies]
pulldown-cmark = "0.1.0"
tempdir = "0.3.5"
jni-sys = "0.3.0"
log = "0.4"
env_logger = "0.5.10"
regex = "0.2.2"

[build-dependencies]
syntex_syntax = "0.58.1"

[badges]
travis-ci = { repository = "Dushistov/rust_swig" }
appveyor = { repository = "Dushistov/rust_swig" }
